name: Build

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version to release (e.g. X.X.X)"
        required: true

permissions:
  contents: write

jobs:
  create-release:
    name: Build and Create Tagged release
    runs-on: ubuntu-latest

    steps:
      - name: Install archive tools
        run: sudo apt-get install -y zip

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - name: Get variables
        id: get_vars
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "DATE=$(date +'%D')" >> $GITHUB_OUTPUT

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: yaca-ui/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: yaca-ui

      - name: Bump package version
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          npm version ${{ inputs.version }} --git-tag-version false
        working-directory: yaca-ui

      - name: Run build
        run: npm run build 
        env:
          CI: false
        working-directory: yaca-ui

      - name: Bundle files alt:V
        run: |
          mkdir -p ./temp/yaca-ui
          cp -r ./yaca-ui/dist/* ./temp/yaca-ui/
          cp -r ./yaca-ui/templates/altV/* ./temp/yaca-ui/
          cd ./temp && zip -r ../yaca-ui-altv.zip ./yaca-ui

      - name: Bundle files for FiveM
        run: |
          mkdir -p ./temp/yaca-ui-fivem
          cp -r ./yaca-ui-fivem/dist/* ./temp/yaca-ui-fivem/
          cp -r ./yaca-ui/templates/fivem/* ./temp/yaca-ui/
          cd ./temp && zip -r ../yaca-ui-fivem.zip ./yaca-ui-fivem

      - name: Update repository
        run: |
          git add .
          git commit -am 'chore: bump version to v${{ inputs.version }}'
          git push

      - name: Create Release
        uses: 'minemalox/automatic-release@v0'
        id: auto_release
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          release_version: 'v${{ inputs.version }}'
          automatic_release_tag: true
          title: 'v${{ inputs.version }}'
          prerelease: false
          files: |
            yaca-ui-altv.zip
            yaca-ui-fivem.zip
          ignore_authors: |
            github-actions[bot]

        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
